### ISSUE TITLE
Capitalized Letters

### ISSUE THREAD

**Issue by Planeshifter** [const-io/pinf-float32#1]
Any specific reason why

```javascript
var pinf = require( 'const-pinf-float32' );
```

is not

```javascript
var PINF = require( 'const-pinf-float32' );
```

instead? Given the convention to capitalize constants, changing this would make copy-pasting the require statement easier.

**Comment by kgryte** [comment]
No. Feel free to make the changes.

**Comment by Planeshifter** [comment]
Done.

**Comment by kgryte** [comment]
Thanks!
